[book]
authors = ["Markus Schröder"]
language = "de"
multilingual = false
src = "src"
title = "Strukturiert Japanisch Lernen"


[output.html]
additional-css = ["all.min.css", "my.css"]
additional-js = []
site-url = "/www/strukturiert_japanisch_lernen/"
